# Analysis - High-Demand, Low_Supply Book Analysis
**Author**: Vuk

## Goal:
Let's analyze library dataset to find the books that have genereted the most borrowings by number pf copies avaliable

## Step 1: Load the dataset
We will use a dataset containig informatio about books:
catalog_position,title,author,year_published,genre,section,total_copies,times_borrowed,
last_borrowed_date,rating,ratings_count,price,language,page_count,dimensions_width,dimensions_thickness,dimensions_height,catalog_shelf,catalog_row,catalog_row_number

In [7]:
import pandas as pd
df = pd.read_csv("books.csv")

## Step 2: Shoe some sample data
Show first 5 rows.

In [8]:
df.head()

,catalog_position,title,author,year_published,genre,section,total_copies,times_borrowed,last_borrowed_date,rating,ratings_count,price,language,page_count,dimensions_width,dimensions_thickness,dimensions_height,catalog_shelf,catalog_row,catalog_row_number
0,A1-B1-0001,Enormous Room,E. E. Cummings,1949.0,Drama,Fiction,5.0,3.0,1/6/2025,4.14,2.0,14.66,en,249.0,4.98,0.60,7.97,A1,B1,1
1,A1-B1-0002,Plutarchi Vitae parallelae,Plutarch,1478.0,Biography & Autobiography,History,4.0,1.0,3/19/2024,NaN,NaN,9.99,en,241.0,5.74,1.12,8.08,A1,B1,2
2,A1-B1-0003,The water-babies,Charles Kingsley,1863.0,Fantasy,Children,6.0,6.0,6/5/2024,4.21,6.0,13.89,en,228.0,7.70,0.70,5.10,A1,B1,3
3,A1-B1-0004,Kipps,H. G. Wells,1900.0,Comedy,Fiction,4.0,5.0,11/6/2024,4.44,4.0,370.00,en,386.0,5.08,0.98,7.80,A1,B1,4
4,A1-B1-0005,Man and Superman,George Bernard Shaw,1903.0,Drama,Fiction,5.0,2.0,1/16/2025,4.46,2.0,10.99,en,220.0,5.08,1.22,7.80,A1,B1,5

## Step 3: Calculate total copies / times borrowed ratio
We are going to create new column (borrowings_per_copy) with *times borrowed* to *total copies* ratio:

In [9]:
df['borrowings_per_copy'] = df['times_borrowed'] / df['total_copies']

## Step 4: Sort and print final results
We are going to sort the values, select fisrt 50 and print the final results.

In [10]:
sorted_df = df.sort_values(by='borrowings_per_copy', ascending=False)
top_50 = sorted_df.head(50)
top_50[['title', 'times_borrowed', 'total_copies', 'borrowings_per_copy']]

,title,times_borrowed,total_copies,borrowings_per_copy
142,Where the Crawdads Sing,2256.0,5.0,451.200000
1010,The Handmaid's Tale,2248.0,5.0,449.600000
1032,Sapiens: A Brief History of Humankind,856.0,2.0,428.000000
1533,Atomic Habits: An Easy & Proven Way to Build G...,1193.0,3.0,397.666667
1051,Atomic Habits,1472.0,4.0,368.000000
231,Inferno,1471.0,4.0,367.750000
1428,The Hunger Games,1287.0,4.0,321.750000
553,The Subtle Art of Not Giving a F*ck,1844.0,6.0,307.333333
1718,The Alchemist,1530.0,5.0,306.000000
1312,Harry Potter and the Half-Blood Prince,1310.0,5.0,262.000000
393,When Breath Becomes Air,775.0,3.0,258.333333
212,Mockingjay,1201.0,5.0,240.200000
1839,Becoming,1419.0,6.0,236.500000
975,The Martian,1396.0,6.0,232.666667
742,Shantaram,454.0,2.0,227.000000
62,Catching Fire,1105.0,5.0,221.000000
1430,Fifty Shades of Grey,1083.0,5.0,216.600000
2026,"Rich Dad, Poor Dad",864.0,4.0,216.000000
271,Fifty Shades Freed,826.0,4.0,206.500000
941,The Power of Habit: Why We Do What We Do in Li...,597.0,3.0,199.000000
970,Gone Girl,1165.0,6.0,194.166667
1784,The Book Thief,1128.0,6.0,188.000000
1276,Fifty Shades Darker,721.0,4.0,180.250000
1540,Harry Potter and the Order of the Phoenix,1061.0,6.0,176.833333
1086,Harry Potter and the Philosopher's Stone,1021.0,6.0,170.166667
396,To Kill a Mockingbird,848.0,5.0,169.600000
437,Sharp Objects,1137.0,7.0,162.428571
1722,Tuesdays with Morrie,646.0,4.0,161.500000
131,A Game of Thrones,590.0,4.0,147.500000
1542,Big Little Lies,1178.0,8.0,147.250000
1089,The Stand,725.0,5.0,145.000000
869,Dune,715.0,5.0,143.000000
266,Harry Potter and the Goblet of Fire,846.0,6.0,141.000000
1052,The Fault in Our Stars,1059.0,8.0,132.375000
124,Being Mortal: Medicine and What Matters in the...,745.0,6.0,124.166667
16,A Thousand Splendid Suns,861.0,7.0,123.000000
1478,Twilight,600.0,5.0,120.000000
1079,Angels & Demons,353.0,3.0,117.666667
63,Divergent,328.0,3.0,109.333333
1933,"Zero to One: Notes on Startups, or How to Buil...",618.0,6.0,103.000000
1822,Und & Use Application Softwr,503.0,5.0,100.600000
766,On Writing: A Memoir of the Craft,197.0,2.0,98.500000
70,The Shining,480.0,5.0,96.000000
1592,The Very Hungry Caterpillar,556.0,6.0,92.666667
284,The Gunslinger,463.0,5.0,92.600000
1391,And the Mountains Echoed,457.0,5.0,91.400000
32,The Immortal Life of Henrietta Lacks,538.0,6.0,89.666667
65,Deception Point,354.0,4.0,88.500000
1200,Hatchet,425.0,5.0,85.000000
237,Fahrenheit 451,505.0,6.0,84.166667

## Conclusion

- the results table shows books with the best times borrowed / total copies ratio
- the library should consider purchasing additional copies of the booksshown in the table